openapi: 3.0.0
info:
  title: API Campañas de Marketing
  version: 1.0.0
  description: Documentación para prueba técnica Fullstack Senior

servers:
  - url: http://localhost:3000/dev
    description: Local server

tags:
  - name: Campaigns
    description: Operaciones relacionadas con campañas de marketing
  - name: Options
    description: Opciones auxiliares para formularios (selects)

paths:
  /campaigns:
    post:
      tags: [Campaigns]
      summary: Crear campaña
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  example: 1
                name:
                  type: string
                  example: "Campaña de verano"
                message_text:
                  type: string
                  example: "¡Aprovecha nuestras ofertas!"
                phone_list:
                  type: string
                  example: "3001234567,3007654321,3001112222"
              required:
                - user_id
                - name
                - message_text
                - phone_list
      responses:
        '201':
          description: Campaña creada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Campaña creada"
                  campaign_id:
                    type: integer
                    example: 42
        '400':
          description: Solicitud inválida
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Parámetros inválidos"
        '500':
          description: Error interno del servidor

    get:
      tags: [Campaigns]
      summary: Listar campañas por rango de fechas
      parameters:
        - in: query
          name: start
          required: true
          schema:
            type: string
            format: date
            example: "2025-05-01"
          description: Fecha inicial (YYYY-MM-DD)
        - in: query
          name: end
          required: true
          schema:
            type: string
            format: date
            example: "2025-05-31"
          description: Fecha final (YYYY-MM-DD)
      responses:
        '200':
          description: Lista de campañas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 42
                    user_id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "Campaña de verano"
                    process_date:
                      type: string
                      format: date
                      example: "2025-05-15"
                    process_status:
                      type: integer
                      description: "1: pendiente, 2: en proceso, 3: finalizada"
                      example: 3
                    phone_list:
                      type: string
                      example: "3001234567,3007654321"
                    message_text:
                      type: string
                      example: "¡Aprovecha nuestras ofertas!"
        '400':
          description: Parámetros inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Faltan parámetros start o end"
        '500':
          description: Error interno del servidor

  /campaigns/{id}/send:
    post:
      tags: [Campaigns]
      summary: Simular envío de campaña
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 42
      responses:
        '200':
          description: Envío simulado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Mensajes enviados exitosamente"
        '404':
          description: Campaña no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Campaña no encontrada"
        '500':
          description: Error interno del servidor

  /campaigns/{id}/messages:
    get:
      tags: [Campaigns]
      summary: Listar mensajes de una campaña
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 42
      responses:
        '200':
          description: Lista de mensajes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1001
                    campaign_id:
                      type: integer
                      example: 42
                    phone:
                      type: string
                      example: "3001234567"
                    text:
                      type: string
                      example: "¡Aprovecha nuestras ofertas!"
                    shipping_status:
                      type: integer
                      description: "1: pendiente, 2: enviado, 3: error"
                      example: 2
                    process_date:
                      type: string
                      format: date
                      example: "2025-05-15"
                    process_hour:
                      type: string
                      example: "14:35:00"
        '404':
          description: Campaña no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "No se encontraron mensajes para esta campaña"
        '500':
          description: Error interno del servidor
  /options/users:
    get:
      tags: [Options]
      summary: Obtener lista de usuarios activos
      responses:
        '200':
          description: Lista de usuarios